-- AlterTable
ALTER TABLE "orders" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "orders" ADD COLUMN "lockedAt" TIMESTAMP(3);
ALTER TABLE "orders" ADD COLUMN "lastModifiedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
