ALTER TABLE "tables"
DROP COLUMN "qrCode",
ADD COLUMN "capacity" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN "qrPayload" TEXT NOT NULL DEFAULT '',
ADD COLUMN "qrCodeUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
